site_name: lmrtfy - Let Me Run That For You
theme:
  name: readthedocs
  highlight_js: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      baselevel: 2
      permalink: "#"

nav:
  - 'index.md'
  - 'about.md'
