site_name: LMRTFY
site_url: https://lmrt.fyi
repo_url: https://github.com/lmrtfy/lmrtfy
site_author: lmrtfy
repo_name: lmrtfy/lmrtfy

docs_dir: 'docs'

theme:
  name: material
  highlight_js: true
  logo: images/lmrtfy_small.png
  favicon: images/favicon.png

  font: false
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  homepage: https://lmrt.fyi

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - abbr
  - admonition
  - attr_list
  - def_list
  - toc:
      baselevel: 2
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - lmrt.fyi: "https://lmrt.fyi"
  - LMRTFY @ GitHub: "https://github.com/lmrtfy/lmrtfy"
  - Introduction: 'index.md'
  - Quickstart: 'quickstart.md'
  - Tutorial:
    - Installation: 'tutorial/installation.md'
    - Login: 'tutorial/login.md'
    - Annotate your script: 'tutorial/annotation.md'
    - Deploy your script/function: 'tutorial/deployment.md'
    - Submit a job: 'tutorial/submission.md'
    - Get results: 'tutorial/fetch_results.md'
  - Examples:
    - Starting Example: 'examples/starting_example.md'
    - Free Fall: 'examples/free_fall.md'
    - Compound Interest: 'examples/compound_interest.md'
  - API Reference:
    - Annotation: "api_reference/annotation.md"
    - Catalog: "api_reference/catalog.md"
  - How to report an issue: "report_bugs.md"
  - Contributing: 'contributing.md'
  #- Roadmap: 'roadmap.md'
  - Changelog: 'CHANGELOG.md'

