site_name: lmrtfy - Let Me Run That For You
site_url: https://www.lmrt.fyi
repo_url: https://github.com/lmrtfy/lmrtfy
site_author: lmrtfy

docs_dir: 'docs'

theme:
  name: readthedocs
  highlight_js: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      baselevel: 2
      permalink: "#"

nav:
  - 'index.md'
  - 'guide.md'
  - 'examples.md'
  - 'about.md'
