name: Bug Report / Enhancement
description: File a bug report or suggest an enhancement.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? What can be improved?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: What system are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - Other
    validations:
      required: true
  - type: input
    id: lmrtfy_version
    attributes:
      label: lmrtfy version
      description: What version of lmrtfy are you running?
    validations:
      required: true
  - type: dropdown
    id: python_version
    attributes:
      label: python version
      description: What python version do you use?
      options:
        - ">=3.11"
        - "3.10"
        - "3.9"
        - "3.8"
        - "3.7"
        - "<3.7"
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot
      description: |      
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
