name: Question
description: Ask a question!
title: "[Question]: "
labels: ["question"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question!
  - type: textarea
    id: question
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Ask us anything.
      value: "Your question."
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: What system are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - Other
    validations:
      required: false
  - type: input
    id: lmrtfy_version
    attributes:
      label: lmrtfy version
      description: What version of lmrtfy are you running?
    validations:
      required: false