name: "Docs - latest"
on:
  push:
    branches:
      - main

env:
  VERSION: "0.0.12"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install -r docs/requirements.txt
          git config user.name gh_pages_bot
          git config user.email gh_pages_bot@lmrtf.fyi
          git fetch origin gh-pages --depth=1
      - run: mike deploy --push --update-alias ${VERSION} latest
