name: publish_to_github_pages
on:
  push:
    branches:
      - test
env:
  VERSION: 0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install -r docs/requirements.txt
          git config user.name gh_pages_bot
          git config user.email gh_pages_bot@lmrtf.fyi
          mike deploy --push --config-file="mkdocs_gh_pages.yml" --update-alias ${VERSION} latest
